### ISSUE TITLE
code dependency wrong

### ISSUE THREAD

**Issue by xbkaishui** [gsyyysg/StockFormer#15]
the code have some dependency issue，  I have fixed it. please check my fork repo
https://github.com/xbkaishui/StockFormer

**Comment by xbkaishui** [comment]
you can contact me by wechat,  my wechat id is xbkaishui

**Comment by yo-yoo** [comment]
Hi, did you meet error when load agent?
Traceback (most recent call last):
File "/content/gdrive/MyDrive/Colab/StockFormer-main/code/train_rl.py", line 224, in <module>
results = DRLAgent.DRL_prediction_load_from_file(model_name='maesac',environment=test_trade_gym, cwd=model_path)
File "/content/gdrive/MyDrive/Colab/StockFormer-main/code/MySAC/models/DRLAgent.py", line 188, in DRL_prediction_load_from_file
raise ValueError("Fail to load agent!")
ValueError: Fail to load agent!
