### ISSUE TITLE
运行train_rl.py中df = fe.preprocess_data(df）似乎因为stockstats报错

### ISSUE THREAD

**Issue by RTkenny** [gsyyysg/StockFormer#2]
![image](https://github.com/gsyyysg/StockFormer/assets/77869923/173b2cf7-4a0c-44f3-83bd-0f9793f4a2fe)

**Comment by RTkenny** [comment]
您好，我对您的理论和实验很感兴趣，我在复现的时候遇到一些问题，很期望您的回复。一开始的时候我按照requirements.txt中的stockstats==0.3.2安装了stockstats，然后在stockstats在from int_date import get_date_from_diff这句代码中报错unable to import get_date_from_diff。随后我将stockstats换为0.4.0，然后再运行train_rl.py就出现了以上的报错，似乎是和add_technical_indicator计算技术因子的函数有关，请问该如何解决呢

**Comment by zlio** [comment]
同样的问题，请问作者如何处理

**Comment by Yanglegezhan** [comment]
> 您好，我对您的理论和实验很感兴趣，我在复现的时候遇到一些问题，很期望您的回复。一开始的时候我按照requirements.txt中的stockstats==0.3.2安装了stockstats，然后在stockstats在from int_date import get_date_from_diff这句代码中报错unable to import get_date_from_diff。随后我将stockstats换为0.4.0，然后再运行train_rl.py就出现了以上的报错，似乎是和add_technical_indicator计算技术因子的函数有关，请问该如何解决呢

我也遇到一样的问题，接下来我将preprocessors.py中第185行                    
indicator_df = indicator_df.append(
                        temp_indicator, ignore_index=True
                    )
的append改为_append即可正常运行

**Comment by 15101051** [comment]
如上面所说，这个问题是pandas更新后取消了append导致的，可以将indicator_df.append都改为 _append 或者使用pd.concat

**Comment by YuyangZhu7** [comment]
> 如上面所说，这个问题是pandas更新后取消了append导致的，可以将indicator_df.append都改为 _append 或者使用pd.concat

Traceback (most recent call last):
  File "train_rl.py", line 67, in <module>
    df = fe.preprocess_data(df)
  File "/weizhenyu/yuyangZhu/StockFormer/code/MySAC/preprocessors.py", line 86, in preprocess_data
    df = self.add_technical_indicator(df)
  File "/weizhenyu/yuyangZhu/StockFormer/code/MySAC/preprocessors.py", line 188, in add_technical_indicator
    df = df.merge(
  File "/root/miniconda3/envs/zyy/lib/python3.8/site-packages/pandas/core/frame.py", line 9345, in merge
    return merge(
  File "/root/miniconda3/envs/zyy/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 107, in merge
    op = _MergeOperation(
  File "/root/miniconda3/envs/zyy/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 704, in __init__
    self._maybe_coerce_merge_keys()
  File "/root/miniconda3/envs/zyy/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 1263, in _maybe_coerce_merge_keys
    raise ValueError(msg)
ValueError: You are trying to merge on object and datetime64[ns] columns. If you wish to proceed you should use pd.concat


你好，修改之后仍然出现了上述问题，不知道如何解决

**Comment by 15101051** [comment]
> > 如上面所说，这个问题是pandas更新后取消了append导致的，可以将indicator_df.append都改为 _append 或者使用pd.concat
> 
> Traceback (most recent call last): File "train_rl.py", line 67, in df = fe.preprocess_data(df) File "/weizhenyu/yuyangZhu/StockFormer/code/MySAC/preprocessors.py", line 86, in preprocess_data df = self.add_technical_indicator(df) File "/weizhenyu/yuyangZhu/StockFormer/code/MySAC/preprocessors.py", line 188, in add_technical_indicator df = df.merge( File "/root/miniconda3/envs/zyy/lib/python3.8/site-packages/pandas/core/frame.py", line 9345, in merge return merge( File "/root/miniconda3/envs/zyy/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 107, in merge op = _MergeOperation( File "/root/miniconda3/envs/zyy/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 704, in **init** self._maybe_coerce_merge_keys() File "/root/miniconda3/envs/zyy/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 1263, in _maybe_coerce_merge_keys raise ValueError(msg) ValueError: You are trying to merge on object and datetime64[ns] columns. If you wish to proceed you should use pd.concat
> 
> 你好，修改之后仍然出现了上述问题，不知道如何解决

不好意思不太清楚，我已经不再做这个了，我之前使用的 `pd.concat` 连接 `DataFrame`。
