### ISSUE TITLE
运行main.py时，add_technical_indicator在计算cci_30指标时抛出异常：float division by zero

### ISSUE THREAD

**Issue by fffanrrr** [gsyyysg/StockFormer#3]
Traceback (most recent call last):
  File "D:\Code\StockFormer-main\code\Transformer\main.py", line 88, in <module>
    data =  data_type_dict[args.data_type](
  File "D:\Code\StockFormer-main\code\Transformer\data\stock_data_handle.py", line 35, in __init__
    self.__read_data__()
  File "D:\Code\StockFormer-main\code\Transformer\data\stock_data_handle.py", line 62, in __read_data__
    df = fe.preprocess_data(df)
  File "D:\Code\StockFormer-main\code\Transformer\utils\preprocess.py", line 86, in preprocess_data
    df = self.add_technical_indicator(df)
  File "D:\Code\StockFormer-main\code\Transformer\utils\preprocess.py", line 212, in add_technical_indicator
    indicator_df[["tic", "date", indicator]], on=["tic", "date"], how="left"
  File "C:\Users\lenovo\anaconda3\lib\site-packages\pandas\core\frame.py", line 3511, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
  File "C:\Users\lenovo\anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 5782, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "C:\Users\lenovo\anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 5842, in _raise_if_missing
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['tic', 'date', 'cci_30'], dtype='object')] are in the [columns]"

**Comment by fffanrrr** [comment]
solved

**Comment by YuyangZhu7** [comment]
> solved

您好，请问是如何解决这个问题的呢

**Comment by fffanrrr** [comment]
不好意思，时间有点太久，我记不得这个了



---- 回复的原邮件 ----
| 发件人 | yuyang ***@***.***> |
| 日期 | 2025年03月26日 23:09 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [gsyyysg/StockFormer] 运行main.py时，add_technical_indicator在计算cci_30指标时抛出异常：float division by zero (Issue #3) |

solved

您好，请问是如何解决这个问题的呢

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

YuyangZhu7 left a comment (gsyyysg/StockFormer#3)

solved

您好，请问是如何解决这个问题的呢
